name: Post YouTube Video to Telegram

permissions:
  contents: write

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour


jobs:
  post-video:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Post YouTube Video to Telegram
        uses: pawanbahuguna/yt2tg/@v1.0.0
        env:
          CHANNEL_ID: ${{ secrets.YT_CHANNEL_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          ALLOW_REPOST: true

      - name: Commit and Push Changes
        if: always()  # Ensure this step runs even if the previous step fails
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add last_video.txt
          git diff --quiet && git diff --staged --quiet || git commit -m "Update last_video.txt with latest video ID"
          git push
